# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: gitlab
description: A Helm chart for GitLab Omnibus
version: 3.1.1
# renovate: image=gitlab/gitlab-ce
appVersion: "16.9.2-ce.0"

home: "https://git.zerolab.link/public/pub/helm-charts/gitlab"
sources:
  - https://docs.gitlab.com
keywords:
  - gitlab
maintainers:
- email: admin@zerolab.link
  name: ZeroLab Project

dependencies:
  - name: base
    version: 1.2.0
    repository: oci://harbor.zerolab.link/library

